"""Add created_at and updated_at to models

Revision ID: 1720e86014a0
Revises: e1f7c2b9a4d3
Create Date: 2026-02-22 21:03:32.648849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1720e86014a0'
down_revision: Union[str, Sequence[str], None] = 'e1f7c2b9a4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.drop_index(op.f('ix_communities_created_by'), table_name='communities')
    op.add_column('community_members', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.drop_index(op.f('ix_community_members_community_id'), table_name='community_members')
    op.drop_index(op.f('ix_community_members_user_id'), table_name='community_members')
    op.add_column('community_post_comments', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.drop_index(op.f('ix_community_post_comments_post_id'), table_name='community_post_comments')
    op.drop_index(op.f('ix_community_post_comments_user_id'), table_name='community_post_comments')
    op.add_column('community_post_likes', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.drop_index(op.f('ix_community_post_likes_post_id'), table_name='community_post_likes')
    op.drop_index(op.f('ix_community_post_likes_user_id'), table_name='community_post_likes')
    op.add_column('community_posts', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.drop_index(op.f('ix_community_posts_community_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_user_id'), table_name='community_posts')
    op.add_column('companies', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('job_analysis', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.drop_index(op.f('ix_job_analysis_resume_id'), table_name='job_analysis')
    op.drop_constraint(op.f('fk_job_analysis_resume_id_resumes'), 'job_analysis', type_='foreignkey')
    op.create_foreign_key(None, 'job_analysis', 'resumes', ['resume_id'], ['id'])
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('resource_lessons', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.drop_index(op.f('ix_resource_lessons_module_id'), table_name='resource_lessons')
    op.add_column('resource_modules', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('resource_modules', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.drop_index(op.f('ix_resource_modules_resource_id'), table_name='resource_modules')
    op.add_column('resources', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.drop_index(op.f('ix_resources_category'), table_name='resources')
    op.drop_index(op.f('ix_resources_created_at'), table_name='resources')
    op.drop_index(op.f('ix_resources_is_published'), table_name='resources')
    op.add_column('resume_embeddings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('resumes', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('user_questionnaires', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.drop_index(op.f('ix_user_stats_user_id'), table_name='user_stats')
    op.drop_constraint(op.f('user_stats_user_id_fkey'), 'user_stats', type_='foreignkey')
    op.create_foreign_key(None, 'user_stats', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'user_stats', type_='foreignkey')
    op.create_foreign_key(op.f('user_stats_user_id_fkey'), 'user_stats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_user_stats_user_id'), 'user_stats', ['user_id'], unique=True)
    op.drop_column('user_questionnaires', 'updated_at')
    op.drop_column('resumes', 'updated_at')
    op.drop_column('resume_embeddings', 'updated_at')
    op.create_index(op.f('ix_resources_is_published'), 'resources', ['is_published'], unique=False)
    op.create_index(op.f('ix_resources_created_at'), 'resources', ['created_at'], unique=False)
    op.create_index(op.f('ix_resources_category'), 'resources', ['category'], unique=False)
    op.drop_column('resources', 'updated_at')
    op.create_index(op.f('ix_resource_modules_resource_id'), 'resource_modules', ['resource_id'], unique=False)
    op.drop_column('resource_modules', 'updated_at')
    op.drop_column('resource_modules', 'created_at')
    op.create_index(op.f('ix_resource_lessons_module_id'), 'resource_lessons', ['module_id'], unique=False)
    op.drop_column('resource_lessons', 'updated_at')
    op.drop_column('posts', 'updated_at')
    op.drop_constraint(None, 'job_analysis', type_='foreignkey')
    op.create_foreign_key(op.f('fk_job_analysis_resume_id_resumes'), 'job_analysis', 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_job_analysis_resume_id'), 'job_analysis', ['resume_id'], unique=False)
    op.drop_column('job_analysis', 'updated_at')
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'created_at')
    op.create_index(op.f('ix_community_posts_user_id'), 'community_posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_community_posts_community_id'), 'community_posts', ['community_id'], unique=False)
    op.drop_column('community_posts', 'updated_at')
    op.create_index(op.f('ix_community_post_likes_user_id'), 'community_post_likes', ['user_id'], unique=False)
    op.create_index(op.f('ix_community_post_likes_post_id'), 'community_post_likes', ['post_id'], unique=False)
    op.drop_column('community_post_likes', 'updated_at')
    op.create_index(op.f('ix_community_post_comments_user_id'), 'community_post_comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_community_post_comments_post_id'), 'community_post_comments', ['post_id'], unique=False)
    op.drop_column('community_post_comments', 'updated_at')
    op.create_index(op.f('ix_community_members_user_id'), 'community_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_community_members_community_id'), 'community_members', ['community_id'], unique=False)
    op.drop_column('community_members', 'updated_at')
    op.create_index(op.f('ix_communities_created_by'), 'communities', ['created_by'], unique=False)
    op.drop_column('communities', 'updated_at')
    # ### end Alembic commands ###
