"""add new tables

Revision ID: 288bb2249a43
Revises: 73a6e7c411b9
Create Date: 2026-01-27 13:58:43.118873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '288bb2249a43'
down_revision: Union[str, Sequence[str], None] = '73a6e7c411b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('dims', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(384), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_embeddings_resume_id'), 'resume_embeddings', ['resume_id'], unique=False)
    op.create_index('ix_resume_embeddings_resume_model', 'resume_embeddings', ['resume_id', 'model_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resume_embeddings_resume_model', table_name='resume_embeddings')
    op.drop_index(op.f('ix_resume_embeddings_resume_id'), table_name='resume_embeddings')
    op.drop_table('resume_embeddings')
    # ### end Alembic commands ###
    op.drop_index(op.f('ix_resume_embeddings_resume_id'), table_name='resume_embeddings')
    op.drop_table('resume_embeddings')
    # ### end Alembic commands ###
