"""Add skill_embeddings: one stored vector per catalog skill and model

Plan 11, D3 / TASK-074. ``SemanticMatchingService`` embedded every skill inside
the request, one sequential call per skill, protected only by an in-process LRU
that Cloud Run empties on every scale-to-zero. With an API provider that is ~50
HTTPS round trips per analysis. The catalog is finite, so each skill is
embedded once in its life and read back from here.

Purely additive: one new table and its indexes. Nothing is backfilled by the
migration — vectors cost a provider call, so they are generated by
``scripts/sync_skill_embeddings.py`` (or lazily on first use), never inside a
deploy. Applying it changes no behaviour on its own.

``uq_skill_embeddings_skill_model`` is what the service's upsert conflicts on:
two requests embedding the same new skill write one row, decided by the
database rather than by a read followed by an insert.

Revision ID: d3e8a1f5c702
Revises: b8f3c05a71d4
Create Date: 2026-10-05
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "d3e8a1f5c702"
down_revision: Union[str, Sequence[str], None] = "b8f3c05a71d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE = "skill_embeddings"
HNSW_INDEX = "ix_skill_embeddings_embedding_hnsw"


def upgrade() -> None:
    bind = op.get_bind()
    # Replayable, like every additive revision since f1a6d3c85e02.
    if sa.inspect(bind).has_table(TABLE):
        return

    is_postgres = bind.dialect.name == "postgresql"
    if is_postgres:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        TABLE,
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "skill_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("skills.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("model_name", sa.String(length=120), nullable=False),
        sa.Column("dims", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(384), nullable=False),
        sa.Column("text_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("fingerprint_version", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "uq_skill_embeddings_skill_model", TABLE, ["skill_id", "model_name"], unique=True
    )
    if is_postgres:
        op.create_index(
            HNSW_INDEX,
            TABLE,
            ["embedding"],
            unique=False,
            postgresql_using="hnsw",
            postgresql_with={"m": "16", "ef_construction": "64"},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        )


def downgrade() -> None:
    # Only regenerable data is lost: every row can be rebuilt by the sync
    # script, at the cost of one embedding call per skill.
    bind = op.get_bind()
    if not sa.inspect(bind).has_table(TABLE):
        return
    if bind.dialect.name == "postgresql":
        op.drop_index(HNSW_INDEX, table_name=TABLE)
    op.drop_index("uq_skill_embeddings_skill_model", table_name=TABLE)
    op.drop_table(TABLE)
